// <auto-generated />
namespace com.agungsetiawan.xpos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class BuatTabelTransaksiInternals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BuatTabelTransaksiInternals));
        
        string IMigrationMetadata.Id
        {
            get { return "201505050753327_BuatTabelTransaksiInternals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
