// <auto-generated />
namespace com.agungsetiawan.xpos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class ubahVarcharDiSupplier : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ubahVarcharDiSupplier));
        
        string IMigrationMetadata.Id
        {
            get { return "201503271034030_ubahVarcharDiSupplier"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
