// <auto-generated />
namespace com.agungsetiawan.xpos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class HapusKolomTotalDiTransaksiInternal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HapusKolomTotalDiTransaksiInternal));
        
        string IMigrationMetadata.Id
        {
            get { return "201505060824045_HapusKolomTotalDiTransaksiInternal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
