// <auto-generated />
namespace com.agungsetiawan.xpos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class InitBarangDanKategori : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitBarangDanKategori));
        
        string IMigrationMetadata.Id
        {
            get { return "201501250135115_InitBarangDanKategori"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
